pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "This the build"
            }
        }
        stage('Test') {
            steps {
                echo "This the test"
            }
            
        }
        
    }
}
