pipeline {
    agent {
        label 'DevServer'
    }
    tools{
        maven 'mymaven'
    }
    parameters {
  choice choices: ['Dev', 'Prod'], name: 'select_environment'
    }

    environment{
        NAME = "Madhu"
    }

    stages {
        stage('Build') {
            steps {
                echo "This the build"
                sh 'mvn clean package -DSkipTests=True'
            }
        }
        stage ('Test'){

            parallel{
                stage('testA'){
                    agent any
                    steps{
                    echo "This is testA"
                    sh 'mvn test'
                    echo "$NAME"
                    }
                }
                stage ('testB'){
                    agent any
                    steps{
                        echo "This is testB"
                        sh 'mvn test'
                    }
                }
                
                }

            post{
                    success{
                    dir ("/mavenproject/target"){
                        stash name: "maven-build" , includes: "*.jar"
                    }
                    }
    
            }
        }
        stage ('deploy'){
            when {expression {params.select_environment == 'dev'}
            beforeAgent true}
            agent {label 'DevServer'}
            steps{
                dir ("/var/www/html"){
                    unstash "maven-build"
                }
                sh """
                    cd /var/ww/html
                    jar -xvf *.jar
                """
            }
        }
        
            
    }
        
    
}
