pipeline {
    agent any
    tools{
        maven 'mymaven'
    }
    parameters{
        string defaultvalue 'Bala' , name 'LASTNAME'
    }
    environment{
        NAME = "Madhu"
    }

    stages {
        stage('Build') {
            steps {
                echo "This the build"
                sh 'mvn clean package'
            }
        }
        stage ('Test'){
            parallel{
                stage('testA'){
                    steps{
                    echo "This is testA"
                    echo "$NAME"
                    }
                }
                stage ('testB'){
                    steps{
                        echo "This is testB"
                    }
                }
                
                }
            post{
                    success{
                    archiveArtifacts artifacts : '**/target/*.jar'
                    }
    
            }
        }
        
            
    }
        
    
}
